import{S as m,i as a}from"./assets/vendor-9310f15c.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const s of e.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerpolicy&&(e.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?e.credentials="include":t.crossorigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function i(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();const d="https://pixabay.com/api/",f="39475716-e1b9a363d760376814942c80f",u=document.getElementById("search-form"),l=document.querySelector(".gallery"),c=new m(".gallery a.lightbox-trigger");l.addEventListener("click",r=>{r.target.classList.contains("lightbox-trigger")&&(r.preventDefault(),c.open())});u.addEventListener("submit",p);function p(r){r.preventDefault();const n=document.querySelector("form input"),o=encodeURIComponent(n.value.trim());if(!o){a.error({title:"Error",message:"Please enter a valid search term.",position:"topRight"});return}const i=document.querySelector(".loading-indicator");i.style.display="block",fetch(`${d}?key=${f}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>{e.hits.length===0?a.warning({title:"No Results",message:"No images found for the given search.",position:"topRight"}):g(e),i.style.display="none"}).catch(e=>{console.error("Fetch error:",e),i.style.display="none",a.error({title:"Error",message:"An error occurred while fetching data.",position:"topRight"})})}function g(r){const n=r.hits.map(o=>`<div class="photo-card">
                <a href="${o.largeImageURL}" class="lightbox-trigger">
                  <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy" />
                </a>
                <div class="info">
                  <p class="info-item"><b>Likes: ${o.likes}</b></p>
                  <p class="info-item"><b>Views: ${o.views}</b></p>
                  <p class="info-item"><b>Comments: ${o.comments}</b></p>
                  <p class="info-item"><b>Downloads: ${o.downloads}</b></p>
                </div>
              </div>`).join("");l.innerHTML=n,c.refresh()}
//# sourceMappingURL=commonHelpers.js.map
